### ISSUE TITLE
Error upon 'npm i' command

### ISSUE THREAD

**Issue by ChonkyWonky** [cheesits456/discord-ssh-bot#1]
told me i needed to update node so i did, is the module supposed to be called server?

`internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module 'semver'
Require stack:
- /usr/share/npm/lib/utils/unsupported.js
- /usr/share/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/share/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/npm/lib/utils/unsupported.js',
    '/usr/share/npm/bin/npm-cli.js'
  ]
}`

**Comment by cheesits456** [comment]
hmm that's a problem within the node installation, not from the code I've written. also, "semver" is short for "semantic versioning", so no, its not supposed to be "server". Im not sure the cause of the problem or how to fix it, but it isn't a problem with the code in this repo

**Comment by ChonkyWonky** [comment]
Yeah I uninstalled node, and reinstalled the latest version five minutes after I posted and it worked perfectly. Thanks anyway.

**Comment by cheesits456** [comment]
Ah okay, glad you got it figured out :)
