### ISSUE TITLE
Error:  Unexpected token

### ISSUE THREAD

**Issue by rowisahub** [cheesits456/discord-ssh-bot#3]
When i run: node index.js : it gives out this

row@minecraft:~/sshish/discord-ssh-bot$ node index.js
/home/row/sshish/discord-ssh-bot/index.js:18
        if (options?.terminal) await (await client.config.channel.fetchWebhooks()).first().send(input, {
                         ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by cheesits456** [comment]
ah, it appears you aren't using nodejs version 14, I'll edit it to give a more appropriate error if your node version is incompatible

**Comment by cheesits456** [comment]
Fixed in b92fc563b218ccac9f8adb9ed56f480c8cad7a65, a proper error message will be displayed if you run this with an incompatible node version

**Comment by rowisahub** [comment]
thanks
