### ISSUE TITLE
Error on running

### ISSUE THREAD

**Issue by Lamaie** [cheesits456/discord-ssh-bot#8]
user@cloudshell:~/discord-ssh-bot$ node index.js
SyntaxError: Unexpected token , in JSON at position 87
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/home/user/discord-ssh-bot/script.js:6:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/user/discord-ssh-bot/index.js:5:2)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)

**Comment by L1me47** [comment]
Node version: v14.15.1

**Comment by L1me47** [comment]
Fixed it but now i'm having the same issue as here https://github.com/cheesits456/discord-ssh-bot/issues/7

**Comment by cheesits456** [comment]
Did you put a valid user ID and a valid channel ID? The values have to be strings as well, not integers

**Comment by cheesits456** [comment]
#7 has been resolved, so I'm gonna close this issue now <3
